---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Skeeto.
--- DateTime: 2019-10-25 4:51 p.m.
---

---
--- Player, a static global class, allows control over in-game players and their hand zones.
---
---@class player

--- The Object class represents any entity within tabletop simulator.
--- Once you have a reference to an object in you're script you can call functions on it directly.
--- Example: obj.getPosition(...).
---
---@class object

---
---Non-exact decimal value.
---
---@class float

---
--- The type *boolean* has two values, **false** and **true**. Both **nil** and
--- **false** make a condition false; any other value makes it true.
---
---@class bool

---
--- No decimals
---
---@class int

---
--- Any of the above Built-in Types.
---
---@class any


