---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Skeeto.
--- DateTime: 2019-10-25 4:39 p.m.
---

---
--- This function is called when a message is sent through the in-game chat.
--- It does not trigger when global chat messages are sent. Using return false inside of this
--- function prevents the chat message which triggered it to be suppressed.
---
---@param message string
---@param sender player
---@return nil
function onChat(message, sender) end

---
--- This function is called when a message is sent through the in-game chat.
--- It does not trigger when global chat messages are sent. Using return false inside of this
--- function prevents the chat message which triggered it to be suppressed.
---
---@param GUID string
---@return object
function getObjectFromGUID(GUID) end